name: Deploy Development Preview
on:
  push:
    branches:
      - dev
      - dev/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: https://totoday-loredapp-guz013.vercel.app/
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.LORED_VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
